#!/usr/bin/expect -f
set timeout 120
set password $env(SSHPASS)
set cmd [lindex $argv 0]
spawn ssh -F /dev/null -o PubkeyAuthentication=no -o StrictHostKeyChecking=no root@121.41.179.197 $cmd
expect {
    "password:" { send "$password\r"; exp_continue }
    "Password:" { send "$password\r"; exp_continue }
    "denied" { exit 1 }
    "Connection closed" { exit 1 }
    eof { exit 0 }
    timeout { exit 2 }
}
expect eof
